### ISSUE TITLE
Make Test failing on Master

### ISSUE THREAD

**Issue by Eoghan1232** [k8snetworkplumbingwg/sriov-network-device-plugin#390]
What happened?
When cloning the main repo, I noticed that when running

make test
The tests failed due to some error
```
FAIL    github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources 
```

```
•••••E1019 09:07:15.126991 1377591 server.go:90] fakename device plugin unable to register with Kubelet : rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing failed to do connect handshake, response: \"HTTP/1.1 503 Service Unavailable\\r\\nContent-Length: 255\\r\\nContent-Type: text/html;charset=utf-8\\r\\nDate: Tue, 19 Oct 2021 13:07:25 GMT\\r\\nMime-Version: 1.0\\r\\nServer: squid/4.16\\r\\nX-Iboss-Error: ERR_DNS_FAIL 0\\r\\n\\r\\n<!doctype html>\\n<html>\\n<head>\\n<meta http-equiv=\\\"refresh\\\" content=\\\"0;url=http://7rx80271.ibosscloud.com/ibreports/ibp/bp.html?bu=https://unix/*&bc=Failed%20to%20retrieve%20requested%20URL.&ip=10.237.222.47&er=ERR_DNS_FAIL\\\"/>\\n</head>\\n<body>\\n</body>\\n</html>\\n\""
•E1019 09:07:15.154981 1377591 server.go:90] fakename device plugin unable to register with Kubelet : rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing failed to do connect handshake, response: \"HTTP/1.1 503 Service Unavailable\\r\\nContent-Length: 255\\r\\nContent-Type: text/html;charset=utf-8\\r\\nDate: Tue, 19 Oct 2021 13:07:25 GMT\\r\\nMime-Version: 1.0\\r\\nServer: squid/4.16\\r\\nX-Iboss-Error: ERR_DNS_FAIL 0\\r\\n\\r\\n<!doctype html>\\n<html>\\n<head>\\n<meta http-equiv=\\\"refresh\\\" content=\\\"0;url=http://7rx80271.ibosscloud.com/ibreports/ibp/bp.html?bu=https://unix/*&bc=Failed%20to%20retrieve%20requested%20URL.&ip=10.237.222.47&er=ERR_DNS_FAIL\\\"/>\\n</head>\\n<body>\\n</body>\\n</html>\\n\""
•E1019 09:07:20.158613 1377591 server.go:223] error. unable to establish test connection with fakename gRPC server: context deadline exceeded
panic: test timed out after 15s

goroutine 138 [running]:
testing.(*M).startAlarm.func1()
        /root/go/src/testing/testing.go:1700 +0xe5
created by time.goFunc
        /root/go/src/time/sleep.go:180 +0x45

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000543380, 0x14bb47c, 0xd, 0x155bc30, 0x498006)
        /root/go/src/testing/testing.go:1239 +0x2da
testing.runTests.func1(0xc000543200)
        /root/go/src/testing/testing.go:1511 +0x78
testing.tRunner(0xc000543200, 0xc0001bbde0)
        /root/go/src/testing/testing.go:1193 +0xef
testing.runTests(0xc00000e270, 0x1eedc00, 0x1, 0x1, 0xc053cea48535dde1, 0x37f02d9bf, 0x1f21980, 0x14bbc41)
        /root/go/src/testing/testing.go:1509 +0x2fe
testing.(*M).Run(0xc00062ee80, 0x0)
        /root/go/src/testing/testing.go:1417 +0x1eb
main.main()
        _testmain.go:45 +0x138

goroutine 6 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x1f21d40)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0xd8

goroutine 7 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1f21ba0)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x274

goroutine 39 [select]:
google.golang.org/grpc.(*ClientConn).WaitForStateChange(0xc00011c000, 0x1673e28, 0xc0002803c0, 0x3, 0x1)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/google.golang.org/grpc@v1.28.1/clientconn.go:502 +0xd4
google.golang.org/grpc.DialContext(0x1673e28, 0xc0002803c0, 0xc00032e180, 0x37, 0xc0001b6df0, 0x2, 0x2, 0x0, 0x0, 0x0)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/google.golang.org/grpc@v1.28.1/clientconn.go:322 +0xd8e
github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources.(*fakeRegistrationServer).dial(0xc000476f00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/workarea/sriov-network-device-plugin/.gopath/src/github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources/testing.go:50 +0x22b
github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources.(*fakeRegistrationServer).registerPlugin(0xc000476f00, 0x0, 0x0)
        /root/workarea/sriov-network-device-plugin/.gopath/src/github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources/testing.go:89 +0x4f
github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources.glob..func1.2(0x1010101)
        /root/workarea/sriov-network-device-plugin/.gopath/src/github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources/server_test.go:87 +0x676
reflect.Value.call(0x13346c0, 0x155bb80, 0x13, 0x14b000e, 0x4, 0xc0000e98c0, 0x4, 0x4, 0x90e, 0x0, ...)
        /root/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x13346c0, 0x155bb80, 0x13, 0xc0000e98c0, 0x4, 0x4, 0x0, 0x0, 0x0)
        /root/go/src/reflect/value.go:337 +0xb9
github.com/onsi/ginkgo/extensions/table.TableEntry.generateIt.func1()
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/extensions/table/table_entry.go:37 +0x57
github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc0000e9980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/leafnodes/runner.go:113 +0xa3
github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc0000e9980, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/leafnodes/runner.go:64 +0x15c
github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc0000ddc80, 0x1648160, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/leafnodes/it_node.go:26 +0x87
github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc000154870, 0x0, 0x1648160, 0xc00003d980)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/spec/spec.go:215 +0x72f
github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc000154870, 0x1648160, 0xc00003d980)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/spec/spec.go:138 +0xf2
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc0000537c0, 0xc000154870, 0x0)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/specrunner/spec_runner.go:200 +0x111
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc0000537c0, 0x1)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/specrunner/spec_runner.go:170 +0x147
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc0000537c0, 0xc00051f010)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/specrunner/spec_runner.go:66 +0x117
github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0000f3220, 0x7f49b798be58, 0xc000543380, 0x14bd9c0, 0xf, 0xc000529140, 0x1, 0x1, 0x1679798, 0xc00003d980, ...)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/suite/suite.go:62 +0x426
github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x1649240, 0xc000543380, 0x14bd9c0, 0xf, 0xc00054d728, 0x1, 0x1, 0x4103d8)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/ginkgo_dsl.go:226 +0x218
github.com/onsi/ginkgo.RunSpecs(0x1649240, 0xc000543380, 0x14bd9c0, 0xf, 0x1131528835c2b9)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/ginkgo_dsl.go:207 +0x168
github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources_test.TestResources(0xc000543380)
        /root/workarea/sriov-network-device-plugin/.gopath/src/github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources/resources_suite_test.go:12 +0x98
testing.tRunner(0xc000543380, 0x155bc30)
        /root/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
        /root/go/src/testing/testing.go:1238 +0x2b3

goroutine 40 [chan receive]:
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).registerForInterrupts(0xc0000537c0, 0xc0000f4a80)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/specrunner/spec_runner.go:223 +0xce
created by github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/specrunner/spec_runner.go:60 +0x86

goroutine 42 [syscall]:
os/signal.signal_recv(0x0)
        /root/go/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
        /root/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /root/go/src/os/signal/signal.go:151 +0x45

goroutine 121 [select]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc00021a580)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/google.golang.org/grpc@v1.28.1/clientconn.go:1125 +0x6cf
created by google.golang.org/grpc.(*addrConn).connect
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/google.golang.org/grpc@v1.28.1/clientconn.go:798 +0x12a

goroutine 120 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00003ca40)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/google.golang.org/grpc@v1.28.1/balancer_conn_wrappers.go:69 +0xac
created by google.golang.org/grpc.newCCBalancerWrapper
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/google.golang.org/grpc@v1.28.1/balancer_conn_wrappers.go:60 +0x172

goroutine 85 [IO wait]:
internal/poll.runtime_pollWait(0x7f49b798bc40, 0x72, 0x0)
        /root/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0002ba398, 0x72, 0x0, 0x0, 0x14b3778)
        /root/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /root/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0002ba380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc0002ba380, 0xc000548f08, 0xc0001aa000, 0x5b0000c000282030)
        /root/go/src/net/fd_unix.go:172 +0x45
net.(*UnixListener).accept(0xc0004775f0, 0x4103d8, 0xc0001aa000, 0xc0001aa088)
        /root/go/src/net/unixsock_posix.go:162 +0x32
net.(*UnixListener).Accept(0xc0004775f0, 0xc000476d50, 0xc000548f08, 0xc0001aa088, 0x0)
        /root/go/src/net/unixsock.go:260 +0x65
google.golang.org/grpc.(*Server).Serve(0xc0002021a0, 0x1672378, 0xc0004775f0, 0x0, 0x0)
        /root/workarea/sriov-network-device-plugin/.gopath/pkg/mod/google.golang.org/grpc@v1.28.1/server.go:621 +0x27f
github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources.(*resourceServer).Start.func1(0xc00020a380, 0x1672378, 0xc0004775f0)
        /root/workarea/sriov-network-device-plugin/.gopath/src/github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources/server.go:213 +0x47
created by github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources.(*resourceServer).Start
        /root/workarea/sriov-network-device-plugin/.gopath/src/github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources/server.go:212 +0x265
FAIL    github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources       15.024s
ok      github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/utils   (cached)
FAIL
make: *** [Makefile:98: test] Error 1

```

What are the minimal steps needed to reproduce the bug?
Clone the repo, and run :

```
make test
```

**Comment by zshi-redhat** [comment]
@Eoghan1232  do you have any proxy configured in the test env? If so, remove them and try again.

**Comment by adrianchiris** [comment]
Closing this one.

1. currently cloning master and running `make test` works in my setup
2. CI is passing
3. issue is old so probably is not relevant anymore

@Eoghan1232  please re open if still relevant.
